services:
  jekyll:
    container_name: arkumunrwdocs
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/app
    command: bundle exec jekyll serve --host 0.0.0.0 --force-polling --livereload